import React from "react";
import {
  MdAdd,
  MdCalendarViewWeek,
  MdClose,
  MdGroups,
  MdInfo,
  MdOutlineCalendarMonth,
  MdPages,
  MdPerson,
  MdShare,
  MdViewCarousel,
  MdWeb,
} from "react-icons/md";
import {
  FaHashtag,
  FaEnvelope,
  FaMapMarkerAlt,
  FaPhone,
  FaInstagram,
  FaYoutube,
  FaSoundcloud,
  FaSpotify,
  FaBandcamp,
  FaTelegramPlane,
  FaTwitter,
  FaFacebook,
  FaGithub,
  FaSearch,
  FaDiscord,
} from "react-icons/fa";
import { IoLogIn, IoTimeSharp } from "react-icons/io5";
import { BiSolidNetworkChart } from "react-icons/bi";
import { IoMdPricetag } from "react-icons/io";
import { ContentTypes } from "./enums";

// Icons mapping for social media and metadata types
export const REACT_ICONS: { [key in ContentTypes]: JSX.Element } = {
  [ContentTypes.discord]: <FaDiscord />,
  [ContentTypes.default]: <></>,
  [ContentTypes.website]: <MdWeb />,
  [ContentTypes.mail]: <FaEnvelope />,
  [ContentTypes.address]: <FaMapMarkerAlt />,
  [ContentTypes.tel]: <FaPhone />,
  [ContentTypes.date]: <MdCalendarViewWeek />,
  [ContentTypes.instagram]: <FaInstagram />,
  [ContentTypes.youtube]: <FaYoutube />,
  [ContentTypes.soundcloud]: <FaSoundcloud />,
  [ContentTypes.price]: <IoMdPricetag />,
  [ContentTypes.spotify]: <FaSpotify />,
  [ContentTypes.facebook]: <FaFacebook />,
  [ContentTypes.bandcamp]: <FaBandcamp />,
  [ContentTypes.telegram]: <FaTelegramPlane />,
  [ContentTypes.twitter]: <FaTwitter />,
  [ContentTypes.add]: <MdAdd />,
  [ContentTypes.name]: <MdPerson />,
  [ContentTypes.time]: <IoTimeSharp />,
  [ContentTypes.connections]: <BiSolidNetworkChart />,
  [ContentTypes.concepts]: <FaHashtag />,
  [ContentTypes.description]: <MdPages />,
  [ContentTypes.category]: <MdGroups />,
  [ContentTypes.collectives]: <MdGroups />,
  [ContentTypes.creatives]: <MdPerson />,
  [ContentTypes.info]: <MdInfo />,
  [ContentTypes.close]: <MdClose />,
  [ContentTypes.share]: <MdShare />,
  [ContentTypes.collaborations]: <MdOutlineCalendarMonth />,
  [ContentTypes.form]: <IoLogIn />,
  [ContentTypes.days]: <MdCalendarViewWeek />,
  [ContentTypes.carousel]: <MdViewCarousel />,
  [ContentTypes.weeks]: <MdCalendarViewWeek />,
  [ContentTypes.github]: <FaGithub />,
  [ContentTypes.search]: <FaSearch />,
};
